#ifndef EVENTS_H_INCLUDED
#define EVENTS_H_INCLUDED

#define S_REQUEST_SERVER_EVENTS 1
#define C_SEND_SERVER_EVENTS 1
#define S_REGISTER_CLIENT_EVENT 2
#define C_CLIENT_EVENT_ACKNOWLEDGEMENT 2

#define S_REQUEST_REGISTER_OBJECT 7
#define C_REGISTRATION_CODE 7

#define SHARED_POSITION 8
#define SHARED_VELOCITY 9
#define SHARED_FRICTION 10
#define SHARED_ROTATION 11
#define SHARED_TEXTUREID 12
#define SHARED_KILL 13

#define C_SINGLE_OBJECT 14

#endif // EVENTS_H_INCLUDED
